"""
General purpose utility functions and classes for the preservation package
"""

class PreservationWarning(Warning):
    """
    a base class for warnings generated by the preservation system
    """
    pass

class ConfigurationWarning(PreservationWarning):
    """
    a warning class that indicates that there appears to be an unnatural 
    configuration (if not strictly erroneous) of the preservation system 
    in place.
    """
    pass

class PreservationException(Exception):
    """
    a base class for exceptions occuring in the preservation system
    """
    pass

class ConfigurationException(PreservationException):
    """
    a class indicating an error in the configuration of the preservation system
    """
    pass

