#! /bin/bash
#
# testall:  run all package tests
#
set -e
prog=`basename $0`
execdir=`dirname $0`
[ "$execdir" = "" -o "$execdir" = "." ] && execdir=$PWD
PACKAGE_DIR=`(cd $execdir/.. > /dev/null 2>&1; pwd)`

# buildtypes="angular python"
buildtypes="python"

dotypes="$@"
[ -n "$dotypes" ] || dotypes=$buildtypes

echo > testall.out

fail=
for bt in $dotypes; do
    if [ -x "$execdir/testall.$bt" ]; then
        echo "Running $bt tests..." | tee -a testall.out
        echo >> testall.out
        echo '+' "$execdir/testall.$bt" | tee -a testall.out
        ("$execdir/testall.$bt"  || fail=$?) 2>&1 | tee -a testall.out
    else
        echo "Testing script for $bt does not exist!" | tee -a testall.out
        fail=2
    fi
done

if [ -n "$fail" ]; then
    echo "Some test(s) failed" | tee -a testall.out
    exit $fail
else
    echo "All OK" | tee -a testall.out
fi
exit 0

        
