name: integration
on:
  workflow_dispatch:
  push:
    branches: [integration]
jobs:
  testall:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Containers
        env:
          OAR_DOCKERHUB_CRED: ${{ secrets.OAR_DOCKERHUB_CRED }}
        run: |
          bash scripts/dhsetup.sh
          cd docker && bash ./dockbuild.sh

      - name: Build & Run Python Tests via Docker
        run: cd docker && ./testall -D python

      - name: Build & Run Java Tests via Docker
        run: cd docker && ./makedist -D java

      - name: Build Angular Code
        run: cd docker && ./makedist -D angular

      - name: Run Angular Tests
        run: cd docker && ./testall -D angular

