name: source-update
on:
  workflow_dispatch:
  push:
    branches-ignore: ['main', 'integration']
    paths:
      - 'java/*/src/**'
      - 'java/*/pom.xml'
jobs:
  buildtest:
    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        java: [ '8' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('java/customization-api/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Test with Maven
        run: cd java/customization-api && mvn --batch-mode test


  
